version: "3.7"
services:
  spring-cloud-config-server:
    container_name: spring-cloud-config-server
    image: singsuyash/spring-cloud-config-server:latest
    environment:
      CLOUD_CONFIG_REPO_URL: https://github.com/singsuyash/spring-cloud-config
    ports:
      - "8888:8888"
    networks:
      - spring-cloud-network

  spring-cloud-config-client:
    container_name: spring-cloud-config-client
    image: singsuyash/spring-cloud-config-client:latest
    environment:
      CONFIG_SERVER_URL: http://spring-cloud-config-server:8888
    depends_on:
      - spring-cloud-config-server
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network

  elastic-search-01:
    container_name: elastic-search-01
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - node.name=elastic-search-01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elastic-search-01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

volumes:
  data01:
    driver: local

networks:
  spring-cloud-network:
    driver: bridge
  elastic:
    driver: bridge
