server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: conditions,env,health,httptrace,info,keepalive,krypt,logfile,refresh,beans,metrics,mappings
---
spring:
  profiles:
  - local
  cloud:
    config:
      server:
        git:
          uri: file:///Users/suyashs/Projects/enterprise-platform/spring-cloud-config
          clone-on-start: true
---
spring:
  profiles:
  - development
  - production
  cloud:
    config:
      server:
        git:
          uri: https://github.com/singsuyash/spring-cloud-config
          clone-on-start: true