# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:
    branches: [ master ]
  
env:
  ORG: singsuyash
  TAG: 1.0.$GITHUB_RUN_NUMBER

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Maven version set
      run: mvn versions:set -DnewVersion=1.0.$GITHUB_RUN_NUMBER
    
    - name: Build with Maven
      run: mvn clean package --file pom.xml
      
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: Build client image
      run: docker build spring-cloud-config-client --file spring-cloud-config-client/Dockerfile --tag spring-cloud-config-client
    - name: Build server image
      run: docker build spring-cloud-config-server --file spring-cloud-config-server/Dockerfile --tag spring-cloud-config-server
    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    - name: Push client image
      run: |
        IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/spring-cloud-config-client
        
        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest

        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION

        docker tag spring-cloud-config-client $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION

    - name: Push server image
      run: |
        IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/spring-cloud-config-server
        
        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest

        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION

        docker tag spring-cloud-config-server $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION